language: ruby
rvm:
  - 2.0.0
  - 2.1.0

before_install:
  - travis_retry gem install bundler
  - export DISABLE_SPRING=1

script:
  - bundle exec rake ci:db:setup
  - bundle exec rake
  - ./bin/ci-rspec spec
  - bundle exec rake test
  - ./bin/ci-test ./test/**/*_test.rb

bundler_args: --path vendor/bundle --without test --jobs 8

notifications:
  email: false
