language: ruby
rvm:
  - 2.0.0
  - 2.1.0

before_install:
  - travis_retry gem install bundler

before_script:
  - mysql -e 'CREATE DATABASE railstutorial_test'
  - mysqladmin --user=rails -f drop railstutorial_test
  - mysql --user=rails -e 'CREATE DATABASE railstutorial_test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci'

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake
  - bundle exec rake test

bundler_args: --path vendor/bundle --without test --jobs 8

notifications:
  email: false
