development: &base
  adapter: mysql2
  username: rails
  database: railstutorial_dev
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  <<: *base
  database: railstutorial_test

production:
  <<: *base
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>
